import pygame, entity

#################################
#Player Units:
#################################

def make_swordsman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/SwordsMan/Walk/WR/1.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/2.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/3.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/4.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/5.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/6.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/7.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/8.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/SwordsMan/Walk/WU/1.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/2.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/3.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/4.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/5.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/6.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/7.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/8.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/SwordsMan/Walk/WL/1.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/2.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/3.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/4.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/5.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/6.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/7.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/8.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/SwordsMan/Walk/WD/1.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/2.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/3.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/4.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/5.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/6.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/7.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/8.png'), pygame.image.load('media/sprites/SwordsMan/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/SwordsMan/Attack/AD/1.png'), pygame.image.load('media/sprites/SwordsMan/Attack/AD/2.png'), pygame.image.load('media/sprites/SwordsMan/Attack/AD/3.png'), pygame.image.load('media/sprites/SwordsMan/Attack/AD/4.png'), pygame.image.load('media/sprites/SwordsMan/Attack/AD/5.png'), pygame.image.load('media/sprites/SwordsMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/SwordsMan/Death/1.png'), pygame.image.load('media/sprites/SwordsMan/Death/2.png'), pygame.image.load('media/sprites/SwordsMan/Death/3.png'), pygame.image.load('media/sprites/SwordsMan/Death/4.png'), pygame.image.load('media/sprites/SwordsMan/Death/5.png'), pygame.image.load('media/sprites/SwordsMan/Death/6.png'), pygame.image.load('media/sprites/SwordsMan/Death/7.png'), pygame.image.load('media/sprites/SwordsMan/Death/8.png'), pygame.image.load('media/sprites/SwordsMan/Death/9.png')]
    char = pygame.image.load('media/sprites/SwordsMan/standing.png')
    standing = pygame.image.load('media/sprites/SwordsMan/standing.png')
    dead = pygame.image.load('media/sprites/SwordsMan/dead.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "player", atk=5, hp=15, spd=3)

def make_archerwoman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/ArcherWoman/Walk/WR/1.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/2.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/3.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/4.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/5.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/6.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/7.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/8.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/ArcherWoman/Walk/WU/1.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/2.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/3.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/4.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/5.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/6.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/7.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/8.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/ArcherWoman/Walk/WL/1.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/2.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/3.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/4.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/5.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/6.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/7.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/8.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/ArcherWoman/Walk/WD/1.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/2.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/3.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/4.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/5.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/6.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/7.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/8.png'), pygame.image.load('media/sprites/ArcherWoman/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/ArcherWoMan/Attack/AD/1.png'), pygame.image.load('media/sprites/ArcherWoMan/Attack/AD/2.png'), pygame.image.load('media/sprites/ArcherWoMan/Attack/AD/3.png'), pygame.image.load('media/sprites/ArcherWoMan/Attack/AD/4.png'), pygame.image.load('media/sprites/ArcherWoMan/Attack/AD/5.png'), pygame.image.load('media/sprites/ArcherWoMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/ArcherWoman/Death/1.png'), pygame.image.load('media/sprites/ArcherWoman/Death/2.png'), pygame.image.load('media/sprites/ArcherWoman/Death/3.png'), pygame.image.load('media/sprites/ArcherWoman/Death/4.png'), pygame.image.load('media/sprites/ArcherWoman/Death/5.png'), pygame.image.load('media/sprites/ArcherWoman/Death/6.png'), pygame.image.load('media/sprites/ArcherWoman/Death/7.png'), pygame.image.load('media/sprites/ArcherWoman/Death/8.png'), pygame.image.load('media/sprites/ArcherWoman/Death/9.png')]
    char = pygame.image.load('media/sprites/ArcherWoman/standing.png')
    guidechar = pygame.image.load('media/outline.png')

    standing = pygame.image.load('media/sprites/ArcherWoman/standing.png')
    dead = pygame.image.load('media/sprites/ArcherWoman/dead.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, attackdist=5, team = "player", hp=5)

def make_elfwoman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/ElfWoman/Walk/WR/1.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/2.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/3.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/4.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/5.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/6.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/7.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/8.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/ElfWoman/Walk/WU/1.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/2.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/3.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/4.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/5.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/6.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/7.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/8.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/ElfWoman/Walk/WL/1.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/2.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/3.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/4.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/5.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/6.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/7.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/8.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/ElfWoman/Walk/WD/1.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/2.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/3.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/4.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/5.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/6.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/7.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/8.png'), pygame.image.load('media/sprites/ElfWoman/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/ElfWoMan/Attack/AD/1.png'), pygame.image.load('media/sprites/ElfWoMan/Attack/AD/2.png'), pygame.image.load('media/sprites/ElfWoMan/Attack/AD/3.png'), pygame.image.load('media/sprites/ElfWoMan/Attack/AD/4.png'), pygame.image.load('media/sprites/ElfWoMan/Attack/AD/5.png'), pygame.image.load('media/sprites/ElfWoMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/ElfWoman/Death/1.png'), pygame.image.load('media/sprites/ElfWoman/Death/2.png'), pygame.image.load('media/sprites/ElfWoman/Death/3.png'), pygame.image.load('media/sprites/ElfWoman/Death/4.png'), pygame.image.load('media/sprites/ElfWoman/Death/5.png'), pygame.image.load('media/sprites/ElfWoman/Death/6.png'), pygame.image.load('media/sprites/ElfWoman/Death/7.png'), pygame.image.load('media/sprites/ElfWoman/Death/8.png'), pygame.image.load('media/sprites/ElfWoman/Death/9.png')]
    char = pygame.image.load('media/sprites/ElfWoman/standing.png')
    guidechar = pygame.image.load('media/outline.png')
    standing = pygame.image.load('media/sprites/ElfWoman/standing.png')
    dead = pygame.image.load('media/sprites/ElfWoman/dead.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "player",spd=7, hp=3, atk=15)

def make_spearman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/SpearsMan/Walk/WR/1.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/2.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/3.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/4.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/5.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/6.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/7.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/8.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/SpearsMan/Walk/WU/1.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/2.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/3.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/4.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/5.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/6.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/7.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/8.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/SpearsMan/Walk/WL/1.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/2.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/3.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/4.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/5.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/6.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/7.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/8.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/SpearsMan/Walk/WD/1.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/2.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/3.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/4.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/5.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/6.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/7.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/8.png'), pygame.image.load('media/sprites/SpearsMan/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/SpearsMan/Attack/AD/1.png'), pygame.image.load('media/sprites/SpearsMan/Attack/AD/2.png'), pygame.image.load('media/sprites/SpearsMan/Attack/AD/3.png'), pygame.image.load('media/sprites/SpearsMan/Attack/AD/4.png'), pygame.image.load('media/sprites/SpearsMan/Attack/AD/5.png'), pygame.image.load('media/sprites/SpearsMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/SpearsMan/Death/1.png'), pygame.image.load('media/sprites/SpearsMan/Death/2.png'), pygame.image.load('media/sprites/SpearsMan/Death/3.png'), pygame.image.load('media/sprites/SpearsMan/Death/4.png'), pygame.image.load('media/sprites/SpearsMan/Death/5.png'), pygame.image.load('media/sprites/SpearsMan/Death/6.png'), pygame.image.load('media/sprites/SpearsMan/Death/7.png'), pygame.image.load('media/sprites/SpearsMan/Death/8.png'), pygame.image.load('media/sprites/SpearsMan/Death/9.png')]
    char = pygame.image.load('media/sprites/SpearsMan/standing.png')
    guidechar = pygame.image.load('media/outline.png')
    standing = pygame.image.load('media/sprites/SpearsMan/standing.png')
    dead = pygame.image.load('media/sprites/SpearsMan/dead.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "player", attackdist=2, hp=18)


def make_wizardman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/WizardMan/Walk/WR/1.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/2.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/3.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/4.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/5.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/6.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/7.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/8.png'), pygame.image.load('media/sprites/WizardMan/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/WizardMan/Walk/WU/1.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/2.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/3.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/4.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/5.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/6.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/7.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/8.png'), pygame.image.load('media/sprites/WizardMan/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/WizardMan/Walk/WL/1.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/2.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/3.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/4.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/5.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/6.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/7.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/8.png'), pygame.image.load('media/sprites/WizardMan/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/WizardMan/Walk/WD/1.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/2.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/3.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/4.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/5.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/6.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/7.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/8.png'), pygame.image.load('media/sprites/WizardMan/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/WizardMan/Attack/AD/1.png'), pygame.image.load('media/sprites/WizardMan/Attack/AD/2.png'), pygame.image.load('media/sprites/WizardMan/Attack/AD/3.png'), pygame.image.load('media/sprites/WizardMan/Attack/AD/4.png'), pygame.image.load('media/sprites/WizardMan/Attack/AD/5.png'), pygame.image.load('media/sprites/WizardMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/WizardMan/Death/1.png'), pygame.image.load('media/sprites/WizardMan/Death/2.png'), pygame.image.load('media/sprites/WizardMan/Death/3.png'), pygame.image.load('media/sprites/WizardMan/Death/4.png'), pygame.image.load('media/sprites/WizardMan/Death/5.png'), pygame.image.load('media/sprites/WizardMan/Death/6.png'), pygame.image.load('media/sprites/WizardMan/Death/7.png'), pygame.image.load('media/sprites/WizardMan/Death/8.png'), pygame.image.load('media/sprites/WizardMan/Death/9.png')]
    char = pygame.image.load('media/sprites/WizardMan/standing.png')
    guidechar = pygame.image.load('media/outline.png')
    standing = pygame.image.load('media/sprites/WizardMan/standing.png')
    dead = pygame.image.load('media/sprites/WizardMan/dead.png')
    return entity.Unit(State, X, Y, 64, 64, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "player",attackdist=9, spd=1, hp=3, atk=1)

#################################
#Enemy Units:
#################################

def make_GoblinMan(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/GoblinMan/Walk/WR/1.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/2.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/3.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/4.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/5.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/6.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/7.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/8.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/GoblinMan/Walk/WU/1.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/2.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/3.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/4.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/5.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/6.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/7.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/8.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/GoblinMan/Walk/WL/1.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/2.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/3.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/4.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/5.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/6.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/7.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/8.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/GoblinMan/Walk/WD/1.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/2.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/3.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/4.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/5.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/6.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/7.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/8.png'), pygame.image.load('media/sprites/GoblinMan/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/GoblinMan/Attack/AD/1.png'), pygame.image.load('media/sprites/GoblinMan/Attack/AD/2.png'), pygame.image.load('media/sprites/GoblinMan/Attack/AD/3.png'), pygame.image.load('media/sprites/GoblinMan/Attack/AD/4.png'), pygame.image.load('media/sprites/GoblinMan/Attack/AD/5.png'), pygame.image.load('media/sprites/GoblinMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/GoblinMan/Death/1.png'), pygame.image.load('media/sprites/GoblinMan/Death/2.png'), pygame.image.load('media/sprites/GoblinMan/Death/3.png'), pygame.image.load('media/sprites/GoblinMan/Death/4.png'), pygame.image.load('media/sprites/GoblinMan/Death/5.png'), pygame.image.load('media/sprites/GoblinMan/Death/6.png'), pygame.image.load('media/sprites/GoblinMan/Death/7.png'), pygame.image.load('media/sprites/GoblinMan/Death/8.png'), pygame.image.load('media/sprites/GoblinMan/Death/9.png')]
    char = pygame.image.load('media/sprites/GoblinMan/standing.png')
    guidechar = pygame.image.load('media/outline.png')
    standing = pygame.image.load('media/sprites/GoblinMan/standing.png')
    dead = pygame.image.load('media/sprites/GoblinMan/dead.png')
    return entity.FighterAi(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "enemy", hp=5,spd=7)

def make_OrkMan(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/OrkMan/Walk/WR/1.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/2.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/3.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/4.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/5.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/6.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/7.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/8.png'), pygame.image.load('media/sprites/OrkMan/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/OrkMan/Walk/WU/1.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/2.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/3.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/4.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/5.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/6.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/7.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/8.png'), pygame.image.load('media/sprites/OrkMan/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/OrkMan/Walk/WL/1.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/2.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/3.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/4.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/5.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/6.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/7.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/8.png'), pygame.image.load('media/sprites/OrkMan/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/OrkMan/Walk/WD/1.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/2.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/3.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/4.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/5.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/6.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/7.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/8.png'), pygame.image.load('media/sprites/OrkMan/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/OrkMan/Attack/AD/1.png'), pygame.image.load('media/sprites/OrkMan/Attack/AD/2.png'), pygame.image.load('media/sprites/OrkMan/Attack/AD/3.png'), pygame.image.load('media/sprites/OrkMan/Attack/AD/4.png'), pygame.image.load('media/sprites/OrkMan/Attack/AD/5.png'), pygame.image.load('media/sprites/OrkMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/OrkMan/Death/1.png'), pygame.image.load('media/sprites/OrkMan/Death/2.png'), pygame.image.load('media/sprites/OrkMan/Death/3.png'), pygame.image.load('media/sprites/OrkMan/Death/4.png'), pygame.image.load('media/sprites/OrkMan/Death/5.png'), pygame.image.load('media/sprites/OrkMan/Death/6.png'), pygame.image.load('media/sprites/OrkMan/Death/7.png'), pygame.image.load('media/sprites/OrkMan/Death/8.png'), pygame.image.load('media/sprites/OrkMan/Death/9.png')]
    char = pygame.image.load('media/sprites/OrkMan/standing.png')
    guidechar = pygame.image.load('media/outline.png')
    standing = pygame.image.load('media/sprites/OrkMan/standing.png')
    dead = pygame.image.load('media/sprites/OrkMan/dead.png')
    return entity.FighterAi(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "enemy",hp=12)

def make_TrollMan(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/TrollMan/Walk/WR/1.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/2.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/3.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/4.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/5.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/6.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/7.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/8.png'), pygame.image.load('media/sprites/TrollMan/Walk/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/TrollMan/Walk/WU/1.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/2.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/3.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/4.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/5.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/6.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/7.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/8.png'), pygame.image.load('media/sprites/TrollMan/Walk/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/TrollMan/Walk/WL/1.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/2.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/3.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/4.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/5.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/6.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/7.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/8.png'), pygame.image.load('media/sprites/TrollMan/Walk/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/TrollMan/Walk/WD/1.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/2.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/3.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/4.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/5.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/6.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/7.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/8.png'), pygame.image.load('media/sprites/TrollMan/Walk/WD/9.png')]
    attack = [pygame.image.load('media/sprites/TrollMan/Attack/AD/1.png'), pygame.image.load('media/sprites/TrollMan/Attack/AD/2.png'), pygame.image.load('media/sprites/TrollMan/Attack/AD/3.png'), pygame.image.load('media/sprites/TrollMan/Attack/AD/4.png'), pygame.image.load('media/sprites/TrollMan/Attack/AD/5.png'), pygame.image.load('media/sprites/TrollMan/Attack/AD/6.png')]
    death = [pygame.image.load('media/sprites/TrollMan/Death/1.png'), pygame.image.load('media/sprites/TrollMan/Death/2.png'), pygame.image.load('media/sprites/TrollMan/Death/3.png'), pygame.image.load('media/sprites/TrollMan/Death/4.png'), pygame.image.load('media/sprites/TrollMan/Death/5.png'), pygame.image.load('media/sprites/TrollMan/Death/6.png'), pygame.image.load('media/sprites/TrollMan/Death/7.png'), pygame.image.load('media/sprites/TrollMan/Death/8.png'), pygame.image.load('media/sprites/TrollMan/Death/9.png')]
    char = pygame.image.load('media/sprites/TrollMan/standing.png')
    guidechar = pygame.image.load('media/outline.png')
    standing = pygame.image.load('media/sprites/TrollMan/standing.png')
    dead = pygame.image.load('media/sprites/TrollMan/dead.png')
    return entity.FighterAi(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown, attack, death, dead, team = "enemy",hp=20, spd=2, atk=7)

    
