import pygame, entity

def make_swordsman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/SwordsMan/WR/1.png'), pygame.image.load('media/sprites/SwordsMan/WR/2.png'), pygame.image.load('media/sprites/SwordsMan/WR/3.png'), pygame.image.load('media/sprites/SwordsMan/WR/4.png'), pygame.image.load('media/sprites/SwordsMan/WR/5.png'), pygame.image.load('media/sprites/SwordsMan/WR/6.png'), pygame.image.load('media/sprites/SwordsMan/WR/7.png'), pygame.image.load('media/sprites/SwordsMan/WR/8.png'), pygame.image.load('media/sprites/SwordsMan/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/SwordsMan/WU/1.png'), pygame.image.load('media/sprites/SwordsMan/WU/2.png'), pygame.image.load('media/sprites/SwordsMan/WU/3.png'), pygame.image.load('media/sprites/SwordsMan/WU/4.png'), pygame.image.load('media/sprites/SwordsMan/WU/5.png'), pygame.image.load('media/sprites/SwordsMan/WU/6.png'), pygame.image.load('media/sprites/SwordsMan/WU/7.png'), pygame.image.load('media/sprites/SwordsMan/WU/8.png'), pygame.image.load('media/sprites/SwordsMan/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/SwordsMan/WL/1.png'), pygame.image.load('media/sprites/SwordsMan/WL/2.png'), pygame.image.load('media/sprites/SwordsMan/WL/3.png'), pygame.image.load('media/sprites/SwordsMan/WL/4.png'), pygame.image.load('media/sprites/SwordsMan/WL/5.png'), pygame.image.load('media/sprites/SwordsMan/WL/6.png'), pygame.image.load('media/sprites/SwordsMan/WL/7.png'), pygame.image.load('media/sprites/SwordsMan/WL/8.png'), pygame.image.load('media/sprites/SwordsMan/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/SwordsMan/WD/1.png'), pygame.image.load('media/sprites/SwordsMan/WD/2.png'), pygame.image.load('media/sprites/SwordsMan/WD/3.png'), pygame.image.load('media/sprites/SwordsMan/WD/4.png'), pygame.image.load('media/sprites/SwordsMan/WD/5.png'), pygame.image.load('media/sprites/SwordsMan/WD/6.png'), pygame.image.load('media/sprites/SwordsMan/WD/7.png'), pygame.image.load('media/sprites/SwordsMan/WD/8.png'), pygame.image.load('media/sprites/SwordsMan/WD/9.png')]
    char = pygame.image.load('media/sprites/SwordsMan/char.png')
    standing = pygame.image.load('media/sprites/SwordsMan/char.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown)

def make_archerwoman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/ArcherWoman/WR/1.png'), pygame.image.load('media/sprites/ArcherWoman/WR/2.png'), pygame.image.load('media/sprites/ArcherWoman/WR/3.png'), pygame.image.load('media/sprites/ArcherWoman/WR/4.png'), pygame.image.load('media/sprites/ArcherWoman/WR/5.png'), pygame.image.load('media/sprites/ArcherWoman/WR/6.png'), pygame.image.load('media/sprites/ArcherWoman/WR/7.png'), pygame.image.load('media/sprites/ArcherWoman/WR/8.png'), pygame.image.load('media/sprites/ArcherWoman/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/ArcherWoman/WU/1.png'), pygame.image.load('media/sprites/ArcherWoman/WU/2.png'), pygame.image.load('media/sprites/ArcherWoman/WU/3.png'), pygame.image.load('media/sprites/ArcherWoman/WU/4.png'), pygame.image.load('media/sprites/ArcherWoman/WU/5.png'), pygame.image.load('media/sprites/ArcherWoman/WU/6.png'), pygame.image.load('media/sprites/ArcherWoman/WU/7.png'), pygame.image.load('media/sprites/ArcherWoman/WU/8.png'), pygame.image.load('media/sprites/ArcherWoman/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/ArcherWoman/WL/1.png'), pygame.image.load('media/sprites/ArcherWoman/WL/2.png'), pygame.image.load('media/sprites/ArcherWoman/WL/3.png'), pygame.image.load('media/sprites/ArcherWoman/WL/4.png'), pygame.image.load('media/sprites/ArcherWoman/WL/5.png'), pygame.image.load('media/sprites/ArcherWoman/WL/6.png'), pygame.image.load('media/sprites/ArcherWoman/WL/7.png'), pygame.image.load('media/sprites/ArcherWoman/WL/8.png'), pygame.image.load('media/sprites/ArcherWoman/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/ArcherWoman/WD/1.png'), pygame.image.load('media/sprites/ArcherWoman/WD/2.png'), pygame.image.load('media/sprites/ArcherWoman/WD/3.png'), pygame.image.load('media/sprites/ArcherWoman/WD/4.png'), pygame.image.load('media/sprites/ArcherWoman/WD/5.png'), pygame.image.load('media/sprites/ArcherWoman/WD/6.png'), pygame.image.load('media/sprites/ArcherWoman/WD/7.png'), pygame.image.load('media/sprites/ArcherWoman/WD/8.png'), pygame.image.load('media/sprites/ArcherWoman/WD/9.png')]
    char = pygame.image.load('media/sprites/ArcherWoman/char.png')
    standing = pygame.image.load('media/sprites/ArcherWoman/char.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown)

def make_elfwoman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/ElfWoman/WR/1.png'), pygame.image.load('media/sprites/ElfWoman/WR/2.png'), pygame.image.load('media/sprites/ElfWoman/WR/3.png'), pygame.image.load('media/sprites/ElfWoman/WR/4.png'), pygame.image.load('media/sprites/ElfWoman/WR/5.png'), pygame.image.load('media/sprites/ElfWoman/WR/6.png'), pygame.image.load('media/sprites/ElfWoman/WR/7.png'), pygame.image.load('media/sprites/ElfWoman/WR/8.png'), pygame.image.load('media/sprites/ElfWoman/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/ElfWoman/WU/1.png'), pygame.image.load('media/sprites/ElfWoman/WU/2.png'), pygame.image.load('media/sprites/ElfWoman/WU/3.png'), pygame.image.load('media/sprites/ElfWoman/WU/4.png'), pygame.image.load('media/sprites/ElfWoman/WU/5.png'), pygame.image.load('media/sprites/ElfWoman/WU/6.png'), pygame.image.load('media/sprites/ElfWoman/WU/7.png'), pygame.image.load('media/sprites/ElfWoman/WU/8.png'), pygame.image.load('media/sprites/ElfWoman/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/ElfWoman/WL/1.png'), pygame.image.load('media/sprites/ElfWoman/WL/2.png'), pygame.image.load('media/sprites/ElfWoman/WL/3.png'), pygame.image.load('media/sprites/ElfWoman/WL/4.png'), pygame.image.load('media/sprites/ElfWoman/WL/5.png'), pygame.image.load('media/sprites/ElfWoman/WL/6.png'), pygame.image.load('media/sprites/ElfWoman/WL/7.png'), pygame.image.load('media/sprites/ElfWoman/WL/8.png'), pygame.image.load('media/sprites/ElfWoman/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/ElfWoman/WD/1.png'), pygame.image.load('media/sprites/ElfWoman/WD/2.png'), pygame.image.load('media/sprites/ElfWoman/WD/3.png'), pygame.image.load('media/sprites/ElfWoman/WD/4.png'), pygame.image.load('media/sprites/ElfWoman/WD/5.png'), pygame.image.load('media/sprites/ElfWoman/WD/6.png'), pygame.image.load('media/sprites/ElfWoman/WD/7.png'), pygame.image.load('media/sprites/ElfWoman/WD/8.png'), pygame.image.load('media/sprites/ElfWoman/WD/9.png')]
    char = pygame.image.load('media/sprites/ElfWoman/char.png')
    standing = pygame.image.load('media/sprites/ElfWoman/char.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown)

def make_spearman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/SpearsMan/WR/1.png'), pygame.image.load('media/sprites/SpearsMan/WR/2.png'), pygame.image.load('media/sprites/SpearsMan/WR/3.png'), pygame.image.load('media/sprites/SpearsMan/WR/4.png'), pygame.image.load('media/sprites/SpearsMan/WR/5.png'), pygame.image.load('media/sprites/SpearsMan/WR/6.png'), pygame.image.load('media/sprites/SpearsMan/WR/7.png'), pygame.image.load('media/sprites/SpearsMan/WR/8.png'), pygame.image.load('media/sprites/SpearsMan/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/SpearsMan/WU/1.png'), pygame.image.load('media/sprites/SpearsMan/WU/2.png'), pygame.image.load('media/sprites/SpearsMan/WU/3.png'), pygame.image.load('media/sprites/SpearsMan/WU/4.png'), pygame.image.load('media/sprites/SpearsMan/WU/5.png'), pygame.image.load('media/sprites/SpearsMan/WU/6.png'), pygame.image.load('media/sprites/SpearsMan/WU/7.png'), pygame.image.load('media/sprites/SpearsMan/WU/8.png'), pygame.image.load('media/sprites/SpearsMan/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/SpearsMan/WL/1.png'), pygame.image.load('media/sprites/SpearsMan/WL/2.png'), pygame.image.load('media/sprites/SpearsMan/WL/3.png'), pygame.image.load('media/sprites/SpearsMan/WL/4.png'), pygame.image.load('media/sprites/SpearsMan/WL/5.png'), pygame.image.load('media/sprites/SpearsMan/WL/6.png'), pygame.image.load('media/sprites/SpearsMan/WL/7.png'), pygame.image.load('media/sprites/SpearsMan/WL/8.png'), pygame.image.load('media/sprites/SpearsMan/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/SpearsMan/WD/1.png'), pygame.image.load('media/sprites/SpearsMan/WD/2.png'), pygame.image.load('media/sprites/SpearsMan/WD/3.png'), pygame.image.load('media/sprites/SpearsMan/WD/4.png'), pygame.image.load('media/sprites/SpearsMan/WD/5.png'), pygame.image.load('media/sprites/SpearsMan/WD/6.png'), pygame.image.load('media/sprites/SpearsMan/WD/7.png'), pygame.image.load('media/sprites/SpearsMan/WD/8.png'), pygame.image.load('media/sprites/SpearsMan/WD/9.png')]
    char = pygame.image.load('media/sprites/SpearsMan/char.png')
    standing = pygame.image.load('media/sprites/SpearsMan/char.png')
    return entity.Unit(State, X, Y, 50, 50, char, standing, walkRight, walkLeft, walkUp, walkDown)

def make_wizardman(State, X, Y):
    walkRight = [pygame.image.load('media/sprites/WizardMan/WR/1.png'), pygame.image.load('media/sprites/WizardMan/WR/2.png'), pygame.image.load('media/sprites/WizardMan/WR/3.png'), pygame.image.load('media/sprites/WizardMan/WR/4.png'), pygame.image.load('media/sprites/WizardMan/WR/5.png'), pygame.image.load('media/sprites/WizardMan/WR/6.png'), pygame.image.load('media/sprites/WizardMan/WR/7.png'), pygame.image.load('media/sprites/WizardMan/WR/8.png'), pygame.image.load('media/sprites/WizardMan/WR/9.png')]
    walkUp = [pygame.image.load('media/sprites/WizardMan/WU/1.png'), pygame.image.load('media/sprites/WizardMan/WU/2.png'), pygame.image.load('media/sprites/WizardMan/WU/3.png'), pygame.image.load('media/sprites/WizardMan/WU/4.png'), pygame.image.load('media/sprites/WizardMan/WU/5.png'), pygame.image.load('media/sprites/WizardMan/WU/6.png'), pygame.image.load('media/sprites/WizardMan/WU/7.png'), pygame.image.load('media/sprites/WizardMan/WU/8.png'), pygame.image.load('media/sprites/WizardMan/WU/9.png')]
    walkLeft = [pygame.image.load('media/sprites/WizardMan/WL/1.png'), pygame.image.load('media/sprites/WizardMan/WL/2.png'), pygame.image.load('media/sprites/WizardMan/WL/3.png'), pygame.image.load('media/sprites/WizardMan/WL/4.png'), pygame.image.load('media/sprites/WizardMan/WL/5.png'), pygame.image.load('media/sprites/WizardMan/WL/6.png'), pygame.image.load('media/sprites/WizardMan/WL/7.png'), pygame.image.load('media/sprites/WizardMan/WL/8.png'), pygame.image.load('media/sprites/WizardMan/WL/9.png')]
    walkDown = [pygame.image.load('media/sprites/WizardMan/WD/1.png'), pygame.image.load('media/sprites/WizardMan/WD/2.png'), pygame.image.load('media/sprites/WizardMan/WD/3.png'), pygame.image.load('media/sprites/WizardMan/WD/4.png'), pygame.image.load('media/sprites/WizardMan/WD/5.png'), pygame.image.load('media/sprites/WizardMan/WD/6.png'), pygame.image.load('media/sprites/WizardMan/WD/7.png'), pygame.image.load('media/sprites/WizardMan/WD/8.png'), pygame.image.load('media/sprites/WizardMan/WD/9.png')]
    char = pygame.image.load('media/sprites/WizardMan/char.png')
    standing = pygame.image.load('media/sprites/WizardMan/char.png')
    return entity.Unit(State, X, Y, 64, 64, char, standing, walkRight, walkLeft, walkUp, walkDown)
    
